/** Emoji de bandera (o ícono) por nombre exacto del equipo en el catálogo. */
const TEAM_FLAGS: Record<string, string> = {
  "MÉXICO": "🇲🇽",
  "SUDÁFRICA": "🇿🇦",
  "COREA DEL SUR": "🇰🇷",
  CHEQUIA: "🇨🇿",
  "CANADÁ": "🇨🇦",
  "BOSNIA Y HERZEGOVINA": "🇧🇦",
  CATAR: "🇶🇦",
  SUIZA: "🇨🇭",
  BRASIL: "🇧🇷",
  MARRUECOS: "🇲🇦",
  "HAITÍ": "🇭🇹",
  ESCOCIA: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "ESTADOS UNIDOS": "🇺🇸",
  PARAGUAY: "🇵🇾",
  AUSTRALIA: "🇦🇺",
  "TURQUÍA": "🇹🇷",
  ALEMANIA: "🇩🇪",
  CURAZAO: "🇨🇼",
  "COSTA DE MARFIL": "🇨🇮",
  ECUADOR: "🇪🇨",
  "PAÍSES BAJOS": "🇳🇱",
  "JAPÓN": "🇯🇵",
  SUECIA: "🇸🇪",
  "TÚNEZ": "🇹🇳",
  "BÉLGICA": "🇧🇪",
  EGIPTO: "🇪🇬",
  "IRÁN": "🇮🇷",
  "NUEVA ZELANDA": "🇳🇿",
  "ESPAÑA": "🇪🇸",
  "CABO VERDE": "🇨🇻",
  "ARABIA SAUDITA": "🇸🇦",
  URUGUAY: "🇺🇾",
  FRANCIA: "🇫🇷",
  SENEGAL: "🇸🇳",
  IRAK: "🇮🇶",
  NORUEGA: "🇳🇴",
  ARGENTINA: "🇦🇷",
  ARGELIA: "🇩🇿",
  AUSTRIA: "🇦🇹",
  JORDANIA: "🇯🇴",
  PORTUGAL: "🇵🇹",
  "REPÚBLICA DEMOCRÁTICA DEL CONGO": "🇨🇩",
  "UZBEKISTÁN": "🇺🇿",
  COLOMBIA: "🇨🇴",
  INGLATERRA: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  CROACIA: "🇭🇷",
  GHANA: "🇬🇭",
  "PANAMÁ": "🇵🇦",
  FWC: "🏆",
  "COCA COLA": "🔴",
};

export function getTeamFlag(team: string): string {
  return TEAM_FLAGS[team] ?? "🏳️";
}
